<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Src\Infrastructure\Property\Models\Property;


class PropertySeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $now = now();
        $properties = [
            [
                'id' => 1,
                'name' => 'Họa tiết',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'name' => 'Loại bảo hành',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'name' => 'Thương hiệu',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'name' => 'Chất liệu',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'name' => 'Loại hộp đựng',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 6,
                'name' => 'Loại da',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 7,
                'name' => 'Chất liệu dây đeo',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 8,
                'name' => 'Khả năng tương thích của Mẫu',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 9,
                'name' => 'Dung lượng Powerbank',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 10,
                'name' => 'Số cổng',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 11,
                'name' => 'Cổng',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 12,
                'name' => 'Các tính năng của Powerbank',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 13,
                'name' => 'Điện áp (V)',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 14,
                'name' => 'Sạc nhanh',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 15,
                'name' => 'Số lượng Bộ sạc',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 16,
                'name' => 'Loại phích cắm',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 17,
                'name' => 'Người mẫu',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 18,
                'name' => 'Các Mẫu Tương thích',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 19,
                'name' => 'Độ phân giải',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 20,
                'name' => 'Dung lượng lưu trữ',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 21,
                'name' => 'Hệ điều hành được Hỗ trợ',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 22,
                'name' => 'Loại cáp',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 23,
                'name' => 'Thời hạn bảo hành',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 24,
                'name' => 'Bó',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 25,
                'name' => 'Điện áp đầu vào (V)',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 26,
                'name' => 'Có pin',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 27,
                'name' => 'Dung lượng pin (mAh)',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 28,
                'name' => 'Có Maganet',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 29,
                'name' => 'Tình trạng sản phẩm',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 30,
                'name' => 'Pin tích hợp',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 31,
                'name' => 'Số lượng pin',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 32,
                'name' => 'Điểm lấy nét Tự động',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 33,
                'name' => 'Kích thước Màn hình',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 34,
                'name' => 'Siêu điểm ảnh',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 35,
                'name' => 'Mẫu Camera',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 36,
                'name' => 'Không thấm nước',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 37,
                'name' => 'Phạm vi Lấy nét Tối thiểu (m)',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 38,
                'name' => 'Phạm vi ISO',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 39,
                'name' => 'Loại pin',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 40,
                'name' => 'Thu phóng Kỹ thuật số',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 41,
                'name' => 'Tỷ lệ Khung',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 42,
                'name' => 'Khẩu độ Tối đa',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 43,
                'name' => 'Loại Thẻ nhớ',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 44,
                'name' => 'Khẩu độ Tối thiểu',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 45,
                'name' => 'Zoom Quang học',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 46,
                'name' => 'Chụp video Nghị quyết',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 47,
                'name' => 'Ống ngắm',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 48,
                'name' => 'Loại Ống kính Camera',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 49,
                'name' => 'Khả năng tương thích với Nhãn hiệu Camera',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 50,
                'name' => 'Dành cho Trò chơi',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 51,
                'name' => 'Loại kết nối',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 52,
                'name' => 'Dành cho Thể thao',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 53,
                'name' => 'Khả năng tương thích Âm thanh',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 54,
                'name' => 'Tai nghe',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 55,
                'name' => 'Tai nghe',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 56,
                'name' => 'Loại Phụ kiện Tai nghe',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 57,
                'name' => 'Loại Kết nối Tai nghe',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 58,
                'name' => 'Phản hồi Tần số Tối đa',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 59,
                'name' => 'Phản hồi Tần số Tối thiểu',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 60,
                'name' => 'Đánh giá Độ nhạy',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 61,
                'name' => 'Loa Thông minh',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 62,
                'name' => 'Bluetooth',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 63,
                'name' => 'Loại âm li',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 64,
                'name' => 'Bộ cắt Âm thanh',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 65,
                'name' => 'Đầu vào',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 66,
                'name' => 'Phạm vi',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 67,
                'name' => 'Số kênh',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 68,
                'name' => 'Kết nối Tai nghe',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 69,
                'name' => 'Nguồn điện',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 70,
                'name' => 'Loại Tai nghe',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 71,
                'name' => 'Mức tiêu thụ điện (W)',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 72,
                'name' => 'Độ sáng Máy chiếu',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 73,
                'name' => 'Tỷ lệ Tương phản',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 74,
                'name' => 'Các tính năng của Máy chiếu',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 75,
                'name' => 'Loại Máy chiếu',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 76,
                'name' => 'Loại Bảng điều khiển Trò chơi',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 77,
                'name' => 'Kết nối',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 78,
                'name' => 'Khả năng tương thích Nền tảng',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 79,
                'name' => 'Đường kính Vỏ Đồng hồ',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 80,
                'name' => 'Kích thước Màn hình (inch)',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 81,
                'name' => 'Đồng hồ Thông minh',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 82,
                'name' => 'Độ phân giải Camera Chính',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 83,
                'name' => 'Chất liệu dây đeo',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 84,
                'name' => 'Xem Kết nối',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 85,
                'name' => 'Bảng điều khiển Tương thích',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 86,
                'name' => 'RAM',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 87,
                'name' => 'Số lượng pin',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 88,
                'name' => 'NFC',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 89,
                'name' => 'Màu sắc',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 90,
                'name' => 'Số lượng Khe cắm Thẻ SIM',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 91,
                'name' => 'Loại Điện thoại',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 92,
                'name' => 'Trọng lượng (g)',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 93,
                'name' => 'Vi xử lý',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 94,
                'name' => 'Số lõi',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 95,
                'name' => 'Loại SIM',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 96,
                'name' => 'Giắc cắm 3,5 mm',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 97,
                'name' => 'Loại giày cao gót',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 98,
                'name' => 'Năm phát hành',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 99,
                'name' => 'CPU (Ghz)',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 100,
                'name' => 'Ổ đĩa quang',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 101,
                'name' => 'Loại bảo quản',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 102,
                'name' => 'Mẫu Máy tính xách tay',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 103,
                'name' => 'Nhà sản xuất Chipset Đồ họa',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 104,
                'name' => 'Kích thước Màn hình Máy tính xách tay',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 105,
                'name' => 'Loại máy tính xách tay',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 106,
                'name' => 'Hệ điều hành',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 107,
                'name' => 'Loại bảng LED',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 108,
                'name' => 'Kích thước Màn hình Điều khiển',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 109,
                'name' => 'Giám sát Thời gian Phản hồi (ms)',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 110,
                'name' => 'Cổng Giám sát',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 111,
                'name' => 'Điện áp',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 112,
                'name' => 'DDR',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 113,
                'name' => 'Số lượng Lõi CPU',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 114,
                'name' => 'Chipset CPU',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 115,
                'name' => 'Đánh giá Công suất',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 116,
                'name' => 'Đánh giá Hiệu suất PSU',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 117,
                'name' => 'Khả năng tương thích của Bo mạch chủ',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 118,
                'name' => 'Bên trong/Bên ngoài',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 119,
                'name' => 'Tốc độ Đọc (Mb/s)',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 120,
                'name' => 'Phương tiện Tương thích',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 121,
                'name' => 'Chế độ Đầu ra Âm thanh',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 122,
                'name' => 'Nước xuất xứ',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 123,
                'name' => 'Mẫu Bàn phím & Chuột',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 124,
                'name' => 'Các tính năng của Cáp',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 125,
                'name' => 'Micro Tích hợp sẵn',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 126,
                'name' => 'Khả năng tương thích với Thương hiệu Bộ sạc Máy tính xách tay',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 127,
                'name' => 'Chiều dài Cáp (m)',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 128,
                'name' => 'Loại Bộ điều hợp',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 129,
                'name' => 'Loại Bút',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 130,
                'name' => 'Tốc độ Quay',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 131,
                'name' => 'Hệ số hình thức SSD',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 132,
                'name' => 'Số lượng Nhịp',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 133,
                'name' => 'Loại Tốc độ Bộ nhớ Flash',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 134,
                'name' => 'Loại Bộ nhớ Flash',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 135,
                'name' => 'Kích thước Vỏ Đĩa cứng (inch)',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 136,
                'name' => 'Số lượng Anten',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 137,
                'name' => 'Loại Ăng ten',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 138,
                'name' => 'Tốc độ Modem (Mbps)',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 139,
                'name' => 'Mạng Không dây',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 140,
                'name' => 'Tốc độ Mạng',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 141,
                'name' => 'Loại Công tắc Mạng',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 142,
                'name' => 'Loại Đầu nối & Cáp mạng',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 143,
                'name' => 'Loại két sắt',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 144,
                'name' => 'Thiết bị thông minh',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 145,
                'name' => 'Tính năng Đồng hồ',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 146,
                'name' => 'Kiểu Theo dõi',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 147,
                'name' => 'Tính năng VR',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 148,
                'name' => 'Tiêu chuẩn Giao tiếp Mạng',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 149,
                'name' => 'Giám sát Thời gian Phản hồi (ms)',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 150,
                'name' => 'Cài đặt',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 151,
                'name' => 'Sử dụng',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 152,
                'name' => 'Số lượng mỗi gói',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 153,
                'name' => 'Đặc điểm',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 154,
                'name' => 'Hình dạng',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 155,
                'name' => 'Phong cách',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 156,
                'name' => 'Kẹp',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 157,
                'name' => 'Số lớp',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 158,
                'name' => 'Trả góp',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 159,
                'name' => 'Trọng lượng hỗ trợ (kg)',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 160,
                'name' => 'Xếp đặt',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 161,
                'name' => 'Số lượng',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 162,
                'name' => 'Tuổi đời sản phẩm',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 163,
                'name' => 'Loại bàn chải toilet',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 164,
                'name' => 'Mùa',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 165,
                'name' => 'Loại bọc ghế nhà vệ sinh',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 166,
                'name' => 'Loại khay đựng xà phòng',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 167,
                'name' => 'Tuổi',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 168,
                'name' => 'Loại giá đỡ bàn chải đánh răng',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 169,
                'name' => 'Loại thanh treo rèm phòng tắm',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 170,
                'name' => 'Loại đĩa xà phòng',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 171,
                'name' => 'Loại bồn tắm',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 172,
                'name' => 'Giới tính',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 173,
                'name' => 'Loại khăn',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 174,
                'name' => 'Loại tiện ích phòng tắm',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 175,
                'name' => 'Bộ phận cơ thể',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 176,
                'name' => 'Loại phụ kiện phòng tắm',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 177,
                'name' => 'Hướng dẫn giặt',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 178,
                'name' => 'Điểm ảnh',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 179,
                'name' => 'Mẫu Ống kính',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 180,
                'name' => 'Loại loa',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 181,
                'name' => 'Loại phụ kiện',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 182,
                'name' => 'Phiên bản',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 183,
                'name' => 'Số lượng Camera Chính',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 184,
                'name' => 'GPS',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 185,
                'name' => 'Dữ liệu di động',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 186,
                'name' => 'Chiều cao bốt',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 187,
                'name' => 'Dịp',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 188,
                'name' => 'Hình dáng ngón chân',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 189,
                'name' => 'Độ rộng của giày',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 190,
                'name' => 'Trang trí',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 191,
                'name' => 'Loại buộc',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 192,
                'name' => 'Loại quai',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 193,
                'name' => 'Chiều cao ủng',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 194,
                'name' => 'Chiều cao phần trên',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 195,
                'name' => 'Loại căn hộ',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 196,
                'name' => 'Đón gót & loại cây',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 197,
                'name' => 'Loại chất tẩy',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 198,
                'name' => 'Thông tin gây dị ứng',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 199,
                'name' => 'Khối lượng tịnh',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 200,
                'name' => 'Chứa cồn hoặc son khí',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 201,
                'name' => 'Khu vực xuất xứ',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 202,
                'name' => 'Thành phần',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 203,
                'name' => 'Hạn sử dụng',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 204,
                'name' => 'Nhượng quyền thương mại',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 205,
                'name' => 'Loại gói',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 206,
                'name' => 'Hình thức sản phẩm',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 207,
                'name' => 'Loại set',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 208,
                'name' => 'Lớp hoàn thiện trang điểm',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 209,
                'name' => 'Lợi ích',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 210,
                'name' => 'Loại dụng cụ trang điểm',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 211,
                'name' => 'Khả năng che phủ khuôn mặt',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 212,
                'name' => 'Màu da',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 213,
                'name' => 'Loại da',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 214,
                'name' => 'SPF',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 215,
                'name' => 'Khu vực áp dụng',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 216,
                'name' => 'Loại sản phẩm tẩy trang',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 217,
                'name' => 'Loại sản phẩm điều trị môi',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 218,
                'name' => 'Ưu tiên thành phần',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 219,
                'name' => 'Loại mặt nạ',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 220,
                'name' => 'Loại dụng cụ chăm sóc da',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 221,
                'name' => 'Kiểu tóc',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 222,
                'name' => 'Loại công cụ tạo kiểu không dùng nhiệt',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 223,
                'name' => 'Ngày hết hạn',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 224,
                'name' => 'Kích cỡ gói',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 225,
                'name' => 'Tuổi khuyến nghị',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 226,
                'name' => 'Đặc tính nguyên liệu',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 227,
                'name' => 'Hương thơm',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 228,
                'name' => 'Loại dụng cụ làm móng tay & móng chân',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 229,
                'name' => 'Loại sản phẩm tắm & chăm sóc cơ thể',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 230,
                'name' => 'Loại trang điểm dành cho nam giới',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 231,
                'name' => 'Loại chăm sóc da cho nam giới',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 232,
                'name' => 'Từ tính',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 233,
                'name' => 'Bao gồm pin',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 234,
                'name' => 'Người lớn hoặc trẻ em',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 235,
                'name' => 'Tính năng của máy sấy tóc',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 236,
                'name' => 'Cảnh báo cẩn thận',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 237,
                'name' => 'Sử dụng cho mục đích y tế hoặc phi y tế',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 238,
                'name' => 'Loại hoạt động',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 239,
                'name' => 'Nếu sửa chữa',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 240,
                'name' => 'Độ cứng của lông',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 241,
                'name' => 'Loại chăm sóc răng giả',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 242,
                'name' => 'Sử dụng ban ngày hoặc ban đêm',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 243,
                'name' => 'Mức dòng chảy',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 244,
                'name' => 'Đặc trưng mùi hương',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 245,
                'name' => 'Cánh',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 246,
                'name' => 'Nhà chế tạo',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 247,
                'name' => 'Độ tuổi',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 248,
                'name' => 'Chiều dài quần áo',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 249,
                'name' => 'Chiều dài tay áo',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 250,
                'name' => 'Vừa vặn',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 251,
                'name' => 'Loại tay áo',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 252,
                'name' => 'Đường viền cổ áo',
                'type' => '4',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 253,
                'name' => 'Kiểu cổ',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 254,
                'name' => 'Loại kích thước',
                'type' => '2',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 255,
                'name' => 'Thiết kế',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 256,
                'name' => 'Loại quần áo',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 257,
                'name' => 'Loại khóa',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 258,
                'name' => 'Kiểu lưng',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 259,
                'name' => 'Chiều dài váy',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 260,
                'name' => 'Chiều cao vòng eo',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 261,
                'name' => 'Chiều dài lai',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 262,
                'name' => 'Loại vạt cài cúc áo',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 263,
                'name' => 'Chủ đề',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 264,
                'name' => 'Loại Knicker',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 265,
                'name' => 'Loại định hình',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 266,
                'name' => 'Kiểu áo ngực',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 267,
                'name' => 'Loại áo ngực',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 268,
                'name' => 'Vị trí khóa trên áo',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 269,
                'name' => 'Độ che kín ngực',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 270,
                'name' => 'Loại phụ kiện áo ngực',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 271,
                'name' => 'Loại đồ lót',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 272,
                'name' => 'Chiều cao vớ',
                'type' => '1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 273,
                'name' => 'Kiểu mũi giày',
                'type' => '3',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 274,
                'name' => 'Tên tổ chức chịu trách nhiệm hàng hóa',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 275,
                'name' => 'Địa chỉ tổ chức chịu trách nhiệm hàng hóa',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 276,
                'name' => 'Văn hoá',
                'type' => '0',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        Property::insert($properties);
    }
}
